import type { LedgerEntry } from './ledgerTypes.js'

const now = Date.now()

export const mockLedgerEntries: LedgerEntry[] = [
  {
    id: 'ledger_payment_job_3_escrow_created',
    paymentId: 'payment_3',
    jobId: 'job-3',
    type: 'escrow_created',
    amount: 3500,
    currency: 'EUR',
    createdAt: now - 1000 * 60 * 60 * 24 * 7,
    note: 'Zahlungsvorgang angelegt (mock)',
  },
  {
    id: 'ledger_payment_job_3_deposit_paid',
    paymentId: 'payment_3',
    jobId: 'job-3',
    type: 'deposit_paid',
    amount: 875,
    currency: 'EUR',
    createdAt: now - 1000 * 60 * 60 * 24 * 6,
    note: 'Anzahlung bestätigt',
  },
  {
    id: 'ledger_payment_job_3_final_paid',
    paymentId: 'payment_3',
    jobId: 'job-3',
    type: 'final_paid',
    amount: 2625,
    currency: 'EUR',
    createdAt: now - 1000 * 60 * 60 * 24 * 2,
    note: 'Restzahlung freigegeben',
  },
  {
    id: 'ledger_payment_job_3_platform_fee',
    paymentId: 'payment_3',
    jobId: 'job-3',
    type: 'platform_fee',
    amount: 420,
    currency: 'EUR',
    createdAt: now - 1000 * 60 * 60 * 24 * 2,
    note: 'SaFix Plattformprovision',
  },
  {
    id: 'ledger_payment_job_3_dispute_resolved_release',
    paymentId: 'payment_3',
    jobId: 'job-3',
    type: 'dispute_resolved_release',
    amount: 3080,
    currency: 'EUR',
    createdAt: now - 1000 * 60 * 60 * 24 * 2,
    note: 'Freigabe nach Streitbeilegung',
    disputeId: 'dispute_3',
  },
  {
    id: 'ledger_payment_job_1_escrow_created',
    paymentId: 'payment_1',
    jobId: 'job-1',
    type: 'escrow_created',
    amount: 2000,
    currency: 'EUR',
    createdAt: now - 1000 * 60 * 60 * 24 * 5,
    note: 'Zahlungsvorgang angelegt (mock)',
  },
  {
    id: 'ledger_payment_job_1_deposit_paid',
    paymentId: 'payment_1',
    jobId: 'job-1',
    type: 'deposit_paid',
    amount: 500,
    currency: 'EUR',
    createdAt: now - 1000 * 60 * 60 * 24 * 4,
    note: 'Anzahlung bestätigt',
  },
  {
    id: 'ledger_payment_job_2_escrow_created',
    paymentId: 'payment_2',
    jobId: 'job-2',
    type: 'escrow_created',
    amount: 1200,
    currency: 'EUR',
    createdAt: now - 1000 * 60 * 60 * 24 * 3,
    note: 'Zahlungsvorgang angelegt (mock)',
  },
  {
    id: 'ledger_payment_job_2_deposit_paid',
    paymentId: 'payment_2',
    jobId: 'job-2',
    type: 'deposit_paid',
    amount: 300,
    currency: 'EUR',
    createdAt: now - 1000 * 60 * 60 * 24 * 2,
    note: 'Anzahlung bestätigt',
  },
]
