-- =============================================================================
-- Prod function-EXECUTE overlay for the pgTAP baseline (grant fidelity, part 2)
-- =============================================================================
-- Same class as the table-grant gap: supabase default privileges GRANT EXECUTE
-- on functions to anon/authenticated at creation time, and production has since
-- REVOKEd EXECUTE for security-sensitive RPCs/trigger functions. A schema dump
-- re-grants them, so the rebuilt baseline lets anon/authenticated execute RPCs
-- that prod forbids — which is what broke test 07 (anon can call get_or_create /
-- inquiry-state RPCs).
--
-- This reconstructs prod's revoked EXECUTE posture: REVOKE EXECUTE on exactly the
-- 172 (function, role) pairs where prod denies it. Generated from prod
-- (pg_proc + has_function_privilege). If a signature is wrong this fails loudly
-- on apply, so it is self-checking.
-- =============================================================================

REVOKE EXECUTE ON FUNCTION public._assert_caller_is_operator() FROM anon;
REVOKE EXECUTE ON FUNCTION public._assert_caller_is_operator() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public._enforce_profile_privileged_columns() FROM anon;
REVOKE EXECUTE ON FUNCTION public.account_cascade_delete_owned_rows(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.account_cascade_delete_owned_rows(p_user_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.account_cascade_list_storage(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.account_cascade_list_storage(p_user_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.apply_dispute_default_refund(p_dispute_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.apply_dispute_default_refund(p_dispute_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.assert_attribution_finalized_before_release() FROM anon;
REVOKE EXECUTE ON FUNCTION public.become_provider(p_company_name text, p_description text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.become_provider(p_company_name text, p_description text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.chat_messages_dispatch_push() FROM anon;
REVOKE EXECUTE ON FUNCTION public.chat_messages_dispatch_push() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.chat_user_is_thread_admin(p_thread_id uuid, p_uid uuid, p_include_craftsman boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.complete_tranche_payout(p_tranche_id text, p_payout_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.complete_tranche_payout(p_tranche_id text, p_payout_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.confirm_funding_atomic(p_funding_request_id uuid, p_escrow_plan_id uuid, p_payment_intent_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.confirm_funding_atomic(p_funding_request_id uuid, p_escrow_plan_id uuid, p_payment_intent_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.confirm_split_proposal(p_proposal_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.confirm_split_proposal(p_proposal_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.create_spatial_offer(p_id uuid, p_scene_id uuid, p_document_type text, p_price numeric, p_net_total numeric, p_gross_total numeric, p_vat_amount numeric, p_vat_rate integer, p_currency text, p_line_items jsonb, p_spatial_metadata jsonb, p_description text, p_conversation_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_team_member_stub(p_provider_id uuid, p_full_name text, p_role text, p_phone text, p_email text, p_weekly_target_hours numeric, p_daily_target_hours numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.deactivate_team_member(p_member_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.dispute_spatial_evidence_append(p_dispute_id uuid, p_scene_id uuid, p_node_id text, p_evidence_kind text, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.enforce_scan_fsm() FROM anon;
REVOKE EXECUTE ON FUNCTION public.enforce_scan_fsm() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.ensure_subscription_row() FROM anon;
REVOKE EXECUTE ON FUNCTION public.epoch_ms() FROM anon;
REVOKE EXECUTE ON FUNCTION public.finalize_payment_state_atomic(p_job_id text, p_target_state text, p_dispute_id text, p_actor text, p_refunded_amount numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_chat_migration_status_set_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_chat_migration_status_set_updated_at() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_chat_set_message_type_on_attachment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_chat_set_message_type_on_attachment() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_chat_update_thread_last_message() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_chat_update_thread_last_message() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_resolve_provider_for_caller() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_resolve_provider_for_caller() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_seed_chat_participants_for_provider(p_thread_id uuid, p_provider_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_seed_chat_participants_for_provider(p_thread_id uuid, p_provider_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_update_thread_last_message() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_update_thread_last_message() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_user_notification_prefs_set_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.fn_user_notification_prefs_set_updated_at() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_invoice_number() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_invoice_number() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_unique_company_code() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_unique_company_code() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_customer_billing_for_invoice(p_job_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_or_create_assignment_thread(p_calendar_entry_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_or_create_office_thread() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_or_create_team_thread() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_auth_user_delete_cascade() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_auth_user_delete_cascade() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.increment_craftsman_jobs_count(p_craftsman_user_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_blocked(user_a uuid, user_b uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_blocked_by_me(target_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_caller_moderation_write_allowed() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_current_user_operator() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_pro_owner(p_profile_id uuid, p_now timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.jobs_terminal_status_guard() FROM anon;
REVOKE EXECUTE ON FUNCTION public.jobs_terminal_status_guard() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.join_company_with_code(p_code text, p_full_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.leave_company() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notification_push_recipient(p_job_id uuid, p_recipient_role text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.notification_push_recipient(p_job_id uuid, p_recipient_role text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.notification_signals_dispatch_push() FROM anon;
REVOKE EXECUTE ON FUNCTION public.notification_signals_dispatch_push() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.offers_mark_quote_stale(p_offer_id uuid, p_reason text, p_source_scene_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.open_dispute_atomic(p_job_id uuid, p_dispute_id uuid, p_reason text, p_description text, p_raised_by text, p_payment_id uuid, p_metadata jsonb, p_context_snapshot jsonb, p_opened_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.operator_enforce_report(p_action text, p_report_id uuid, p_target_user_id uuid, p_notes text, p_suspend_hours integer, p_target_message_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.operator_mark_dispute_under_review(p_dispute_id uuid, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.operator_reject_dispute(p_dispute_id uuid, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.operator_request_customer_evidence_dispute(p_dispute_id uuid, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.operator_request_provider_evidence_dispute(p_dispute_id uuid, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.operator_resolve_attribution(p_job_id uuid, p_mode text, p_to_origin text, p_reason text, p_operator_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.operator_resolve_attribution(p_job_id uuid, p_mode text, p_to_origin text, p_reason text, p_operator_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.operator_resolve_dispute_refund(p_dispute_id uuid, p_note text, p_refund_amount numeric, p_release_amount numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.operator_resolve_dispute_release(p_dispute_id uuid, p_note text, p_release_amount numeric, p_refund_amount numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.operator_resolve_dispute_split(p_dispute_id uuid, p_split_ratio numeric, p_note text, p_provider_award_amount numeric, p_customer_refund_amount numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.party_submit_dispute_statement(p_dispute_id uuid, p_evidence jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.propose_split_atomic(p_dispute_id uuid, p_ratio numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.propose_split_atomic(p_dispute_id uuid, p_ratio numeric) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.reactivate_team_member(p_member_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reassign_job_member(p_job_id uuid, p_from text, p_to text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reconcile_transfer_reversal_atomic(p_tranche_id uuid, p_plan_id uuid, p_reversal_ref text, p_reversed_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reconcile_transfer_reversal_atomic(p_tranche_id uuid, p_plan_id uuid, p_reversal_ref text, p_reversed_at timestamp with time zone) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.record_push_action_attempt(p_notification_id uuid, p_action_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.record_scan_event(p_scan_id uuid, p_action scan_event_action, p_payload jsonb, p_idempotency_key uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reject_split_proposal(p_proposal_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reject_split_proposal(p_proposal_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.release_tranche_atomic(p_tranche_id uuid, p_plan_id uuid, p_transfer_id text, p_actor text, p_released_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.release_tranche_atomic(p_tranche_id uuid, p_plan_id uuid, p_transfer_id text, p_actor text, p_released_at timestamp with time zone) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.release_tranche_with_ledger(p_tranche_id text, p_plan_id text, p_transfer_id text, p_actor text, p_released_at timestamp with time zone, p_net_amount numeric, p_currency text, p_payment_id text, p_job_id text, p_ledger_entry_id text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.release_tranche_with_ledger(p_tranche_id text, p_plan_id text, p_transfer_id text, p_actor text, p_released_at timestamp with time zone, p_net_amount numeric, p_currency text, p_payment_id text, p_job_id text, p_ledger_entry_id text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.request_scan_download(p_scan_id uuid, p_kind text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.resign_download_url(p_job_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rotate_company_code(p_provider_id uuid, p_reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_enqueue_thread_migration(p_legacy_thread_id text, p_legacy_source text, p_priority integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_get_or_create_chat_assignment_thread(p_calendar_entry_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_get_or_create_chat_customer_thread(p_craftsman_user_id uuid, p_title text, p_inquiry_origin text, p_source_project_id text, p_inquiry_criteria jsonb, p_display_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_get_or_create_chat_dispute_thread(p_dispute_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_get_or_create_chat_office_thread() FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_get_or_create_chat_team_thread() FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_send_chat_message_with_attachments(p_thread_id uuid, p_client_message_id uuid, p_body text, p_reply_to_message_id uuid, p_attachments jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.rpc_update_chat_thread_inquiry_state(p_thread_id uuid, p_reviewed_at bigint, p_declined_at bigint) FROM anon;
REVOKE EXECUTE ON FUNCTION public.run_quality_engine(p_scan_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.saved_reels_count_by_folder() FROM anon;
REVOKE EXECUTE ON FUNCTION public.settle_consensus_split(p_dispute_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.settle_consensus_split(p_dispute_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.settle_dispute_default(p_dispute_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.settle_dispute_default(p_dispute_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.settle_dispute_resolution(p_dispute_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.settle_dispute_resolution(p_dispute_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_can_convert_scan(p_scan_id uuid, p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_can_edit_scan(p_scan_id uuid, p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_can_edit_scene(p_scene_id uuid, p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_can_view_mesh_snapshot(p_object_name text, p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_can_view_scan(p_scan_id uuid, p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_can_view_scene(p_scene_id uuid, p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_create_manual_scene(p_id uuid, p_presales_project_id uuid, p_parametric_storage_path text, p_parametric_sha256 text, p_parametric_size_bytes integer, p_origin text, p_metadata jsonb, p_schema_version text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_create_scene(p_id uuid, p_parametric_storage_path text, p_parametric_sha256 text, p_parametric_size_bytes integer, p_source_scan_id uuid, p_source_job_id uuid, p_schema_version text, p_validation_state text, p_validation_report jsonb, p_is_renderable boolean, p_requires_user_confirmation boolean, p_metadata jsonb, p_parent_scene_id uuid, p_rescan_request_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_edit_history_append(p_scene_id uuid, p_variant_id text, p_base_node_id text, p_override_fields jsonb, p_command text, p_sha_before text, p_sha_after text, p_semantic_op text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_get_convert_push_secret() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_get_convert_push_secret() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_idempotency_cleanup() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_idempotency_cleanup() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_is_customer_viewer(p_scan_id uuid, p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_is_job_craftsman(p_scan_id uuid, p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_is_job_worker(p_scan_id uuid, p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_is_operator(p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_log_provider_share_action() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_log_provider_share_action() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_log_share_action() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_log_share_action() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_notify_convert_done() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_notify_convert_done() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_parametric_cleanup_dispatch() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_parametric_cleanup_dispatch() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_parametric_cleanup_list_orphans(p_grace_days integer, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_parametric_cleanup_list_orphans(p_grace_days integer, p_limit integer) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_realtime_uuid_pat() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_reap_stuck_download_jobs() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_reap_stuck_download_jobs() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_rescan_request_respond(p_request_id uuid, p_status text, p_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_broadcast() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_broadcast() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_cleanup_dispatch() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_cleanup_dispatch() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_cleanup_list_expired(p_retention_days integer, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_cleanup_list_expired(p_retention_days integer, p_limit integer) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_cleanup_list_orphans(p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_cleanup_list_orphans(p_limit integer) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_event_broadcast() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_event_broadcast() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_is_locked(p_scan_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_quality_broadcast() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_quality_broadcast() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_scan_storage_path_ok(p_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_scenes_fill_provider_org() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_scenes_fill_provider_org() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.spatial_set_customer_verify_state(p_scene_id uuid, p_state text, p_stage integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_user_org_owner_profile(p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_user_provider_org(p_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_user_team_role(p_uid uuid, p_provider_org_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_verify_reminder_tick() FROM anon;
REVOKE EXECUTE ON FUNCTION public.spatial_verify_reminder_tick() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.start_trial() FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_provider_media_cover() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_team_member(p_member_id uuid, p_full_name text, p_role text, p_phone text, p_email text, p_weekly_target_hours numeric, p_daily_target_hours numeric) FROM anon;
