import type { PaymentState } from '../../lib/shared/coreTypes'
import type { JobCommercialOrigin } from '../../lib/commercialAttribution/types'
import type { RoomScanMetadata } from '../../lib/roomScan/types'

export type ProjectCaseStatus =
  | 'request'
  | 'accepted'
  | 'scheduled'
  | 'in_progress'
  | 'review'
  | 'completed'
  | 'cancelled'

/**
 * Records the origin channel through which this project was created.
 * 'builder'  – customer used the guided project-builder flow
 * 'inquiry'  – project was created from an explore/reel/profile inquiry
 * 'direct'   – project was created directly (legacy / craftsman-side)
 */
export type ProjectCaseSource = 'builder' | 'inquiry' | 'direct'

export type ProjectCase = {
  id: string
  sourceJobId: string
  title: string
  customer: string
  craftsman: string
  location: string
  dateLabel: string
  /**
   * DENORMALIZED DISPLAY FIELD — not canonical truth.
   *
   * This field is a convenience copy of the accepted Offer's price, written
   * at project creation time for list-view display without requiring a
   * cross-domain join.  It may drift from the Offer after a ChangeOrder is
   * accepted.
   *
   * CANONICAL TRUTH: `resolveCanonicalProjectFacts(sourceJobId).canonicalAmount`
   * (which reads from EscrowPlan → Offer → Job in dominance order).
   *
   * Rule: never derive business logic from this field.  Use it only for
   * display fallback when the canonical resolver returns null (e.g. before
   * the Job is linked to the Project).
   */
  price: string
  status: ProjectCaseStatus
  /**
   * DENORMALIZED DISPLAY FIELD — not canonical truth.
   *
   * This field is synced from the underlying Job's payment state via
   * `projectJobSyncBridge` and `projectStatusSync`.  It may be stale during
   * the window between a payment transition and the next bridge cycle.
   *
   * CANONICAL TRUTH: Payment entity — read via `getPaymentForJob(sourceJobId)`.
   * The `deriveCanonicalProjection(project)` resolver applies funded-dominance
   * and overrides this field when a stronger truth exists.
   *
   * Rule: never derive financial business logic from this field.  All screens
   * must use `deriveCanonicalProjection` or the payment selectors.
   */
  paymentState: PaymentState
  messageCount: number
  noteCount: number
  photoCount: number
  createdAt: number
  updatedAt: number

  // ── Ownership ─────────────────────────────────────────────────────────────
  /**
   * Supabase auth.users UUID of the customer who created this project.
   * Set at project-creation time by the builder workflow.
   * Present on all builder-origin projects; absent on legacy rows that
   * predate this column.
   */
  customerUserId?: string
  /**
   * Supabase auth.users UUID of the craftsman who owns this project.
   * Set when a project is linked to a job via convertInquiryToProjectWorkflow.
   * NULL for builder-origin projects that have not yet been accepted by a craftsman.
   */
  craftsmanUserId?: string
  /**
   * Friendly identifier generated by the builder flow for UI/diagnostics only.
   * Not persisted to Supabase — the canonical primary key is the UUID in `id`.
   */
  builderId?: string

  // ── Builder-origin structured fields ──────────────────────────────────────
  /** Where the project originated. Present on all new projects; absent on legacy ones. */
  source?: ProjectCaseSource
  /** Trade category (e.g. "Elektrik", "Bad"). Set by the builder flow. */
  category?: string
  /** Free-text description of the required work. Set by the builder flow. */
  description?: string
  /** Customer-provided budget expectation (e.g. "unter 2.000 €"). */
  requestedBudget?: string
  /** Customer-provided timing preference (e.g. "Innerhalb 4 Wochen"). */
  requestedTiming?: string
  /**
   * Trade-specific structured answers from the guided builder flow.
   * Each entry maps a question key to its human-readable label + value.
   * Absent on legacy projects or projects created without the guided flow.
   */
  tradeSpecificAnswers?: Array<{ key: string; label: string; value: string }>
  /**
   * The commercial origin of the customer↔craftsman relationship for this project.
   * Inherited from `customer_provider_relationships.commercial_origin` at project
   * creation time (during inquiry→job conversion for auto-projects, or at
   * offer acceptance for profile-origin projects).
   *
   * merchant_brought  — craftsman brought this customer into SaFix (5% fee)
   * platform_acquired — SaFix acquired this customer organically (9% fee)
   *
   * Absent on builder-origin projects before a craftsman has been linked,
   * and on legacy projects created before this model was introduced.
   */
  commercialOrigin?: JobCommercialOrigin

  // ── LiDAR room scan ───────────────────────────────────────────────────────
  /** Public Supabase Storage URL of the USDZ scan file. Null if no scan taken. */
  roomScanUrl?: string
  /** Structured scan data extracted from RoomPlan. Null if no scan taken. */
  roomScanMetadata?: RoomScanMetadata
}
