import type { Job, TeamMember } from './types'

export const teamMembersMock: TeamMember[] = [
  { id: 'tm-1', name: 'Leon Becker', role: 'Elektriker' },
  { id: 'tm-2', name: 'Murat Yilmaz', role: 'Monteur' },
  { id: 'tm-3', name: 'Sven Krause', role: 'Installateur' },
  { id: 'tm-4', name: 'Ali Demir', role: 'Azubi' },
]

export const jobsMock: Job[] = [
  {
    id: 'job-1',
    projectId: 'project-1',
    title: 'Badsanierung – Leitungen prüfen',
    customer: 'Max Mustermann',
    location: 'Hannover-Linden',
    dateLabel: 'Heute, 14:00 Uhr',
    status: 'in_progress',
    amount: '2.300 €',
    description:
      'Prüfung und Vorbereitung der Leitungen im Rahmen einer laufenden Badsanierung. Kunde erwartet Rückmeldung zum nächsten Arbeitsschritt noch heute.',
    paymentState: 'in_escrow',
    documentationStatus: '2 Fotos vorhanden',
    assignedMemberIds: ['tm-1', 'tm-2'],
    notes: ['Leitungen im Bad geöffnet und Zustand dokumentiert.'],
    photoCount: 2,
    activities: [
      {
        id: 'act-1',
        type: 'system',
        text: 'Auftrag wurde angelegt.',
        createdAtLabel: 'Heute, 09:10',
      },
      {
        id: 'act-2',
        type: 'payment',
        text: 'Anzahlung wurde gesichert.',
        createdAtLabel: 'Heute, 09:42',
      },
      {
        id: 'act-3',
        type: 'status',
        text: 'Status wurde auf „In Arbeit“ gesetzt.',
        createdAtLabel: 'Heute, 10:05',
      },
    ],
  },
  {
    id: 'job-2',
    projectId: 'project-2',
    title: 'Sicherungskasten austauschen',
    customer: 'Anna Becker',
    location: 'Hannover-Mitte',
    dateLabel: 'Morgen, 09:30 Uhr',
    status: 'scheduled',
    proposalAcceptedAt: 1741824000000,
    amount: '1.200 €',
    description:
      'Bestehender Sicherungskasten wird ersetzt. Kunde wurde terminiert und wartet auf Durchführung vor Ort.',
    paymentState: 'deposit_required',
    documentationStatus: 'Noch keine Dokumentation',
    assignedMemberIds: ['tm-3'],
    notes: [],
    photoCount: 0,
    activities: [
      {
        id: 'act-4',
        type: 'system',
        text: 'Auftrag wurde angelegt.',
        createdAtLabel: 'Gestern, 15:30',
      },
      {
        id: 'act-5',
        type: 'status',
        text: 'Status wurde auf „Geplant“ gesetzt.',
        createdAtLabel: 'Gestern, 16:10',
      },
    ],
  },
  {
    id: 'job-3',
    projectId: 'project-3',
    title: 'Wasseranschluss Küche',
    customer: 'Tobias Klein',
    location: 'Hannover-Nordstadt',
    dateLabel: 'Anfrage neu',
    status: 'new',
    amount: '640 €',
    description:
      'Neuanfrage für Anschluss einer neuen Küche. Umfang und genauer Termin müssen noch bestätigt werden.',
    paymentState: 'deposit_required',
    documentationStatus: 'Noch keine Dokumentation',
    assignedMemberIds: [],
    notes: [],
    photoCount: 0,
    intakeContext: {
      origin: 'inquiry_profile',
      originLabel: 'Handwerkerprofil',
      requestDescription:
        'Ich habe eine neue Einbauküche und brauche Anschlüsse für Spüle, Geschirrspüler und Kühlschrank. Außerdem soll eine neue Steckdosenschiene hinter die Küchenzeile verlegt werden.',
      requestLocation: 'Hannover-Nordstadt',
      requestBudget: '500 – 800 €',
      requestDuration: '1–2 Tage',
    },
    activities: [
      {
        id: 'act-6',
        type: 'system',
        text: 'Anfrage wurde neu erfasst.',
        createdAtLabel: 'Heute, 11:18',
      },
    ],
  },
  {
    id: 'job-4',
    projectId: 'project-4',
    title: 'Heizkörper entlüften & prüfen',
    customer: 'Julia Neumann',
    location: 'Hannover-Südstadt',
    dateLabel: 'Gestern abgeschlossen',
    status: 'waiting_payment',
    amount: '290 €',
    description:
      'Arbeit wurde abgeschlossen. Dokumentation ist vorhanden, Zahlung steht noch aus.',
    paymentState: 'release_pending',
    documentationStatus: 'Abschluss dokumentiert',
    assignedMemberIds: ['tm-2'],
    notes: ['Abschluss durchgeführt, Kunde informiert.'],
    photoCount: 1,
    activities: [
      {
        id: 'act-7',
        type: 'system',
        text: 'Auftrag wurde angelegt.',
        createdAtLabel: 'Gestern, 13:10',
      },
      {
        id: 'act-8',
        type: 'status',
        text: 'Status wurde auf „Wartet auf Zahlung“ gesetzt.',
        createdAtLabel: 'Gestern, 16:12',
      },
    ],
  },
  {
    id: 'job-5',
    projectId: 'project-5',
    title: 'Steckdosen nachrüsten',
    customer: 'Daniel Wolf',
    location: 'Hannover-List',
    dateLabel: 'Abgeschlossen',
    status: 'completed',
    amount: '510 €',
    description:
      'Zusätzliche Steckdosen wurden installiert. Auftrag ist vollständig erledigt.',
    paymentState: 'released',
    workCompletedAt: Date.now() - 1000 * 60 * 60 * 24 - 1000 * 60 * 90,
    paymentReleasedAt: Date.now() - 1000 * 60 * 60 * 24,
    documentationStatus: 'Vollständig dokumentiert',
    assignedMemberIds: ['tm-1'],
    notes: ['Arbeit sauber abgeschlossen und geprüft.'],
    photoCount: 3,
    activities: [
      {
        id: 'act-9',
        type: 'system',
        text: 'Auftrag wurde angelegt.',
        createdAtLabel: 'Montag, 08:20',
      },
      {
        id: 'act-10',
        type: 'status',
        text: 'Status wurde auf „Abgeschlossen“ gesetzt.',
        createdAtLabel: 'Montag, 12:02',
      },
      {
        id: 'act-11',
        type: 'payment',
        text: 'Zahlung wurde als „Ausgezahlt“ markiert.',
        createdAtLabel: 'Montag, 12:30',
      },
    ],
  },
]
