import { lazy } from 'react'

export const CustomerHomeScreen = lazy(() => import('./CustomerHomeScreen'))
export const ExploreFeed = lazy(() => import('./ExploreFeed'))
export const ExploreCraftsmanProfileScreen = lazy(() => import('./ExploreCraftsmanProfileScreen'))
export const MessagesScreen = lazy(() => import('./MessagesScreen'))
export const MessageThreadScreen = lazy(() => import('./MessageThreadScreen'))
export const ProfileScreen = lazy(() => import('./ProfileScreen'))
export const LoginScreen = lazy(() => import('./LoginScreen'))
export const AuthCallbackScreen = lazy(() => import('./AuthCallbackScreen'))

export const RoleSelectionScreen = lazy(() => import('./RoleSelectionScreen'))
export const CraftsmanRoleSelectionScreen = lazy(() => import('./CraftsmanRoleSelectionScreen'))

export const CraftsmanDashboardScreen = lazy(() => import('./CraftsmanDashboardScreen'))
export const CraftsmanBackofficeScreen = lazy(() => import('./CraftsmanBackofficeScreen'))
export const CraftsmanJobsScreen = lazy(() => import('./CraftsmanJobsScreen'))
export const CraftsmanJobDetailScreen = lazy(() => import('./CraftsmanJobDetailScreen'))
export const CraftsmanRequestDetailScreen = lazy(() => import('./CraftsmanRequestDetailScreen'))
export const CraftsmanMessagesScreen = lazy(() => import('./CraftsmanMessagesScreen'))
export const CraftsmanMessageThreadScreen = lazy(() => import('./CraftsmanMessageThreadScreen'))
export const CraftsmanFinanceScreen = lazy(() => import('./CraftsmanFinanceScreen'))
export const CraftsmanInvoicesScreen = lazy(() => import('./CraftsmanInvoicesScreen'))
export const DisputeCenterScreen = lazy(() => import('./DisputeCenterScreen'))
export const OperatorDashboardScreen = lazy(() => import('./OperatorDashboardScreen'))

export const WorkerHomeScreen = lazy(() => import('./WorkerHomeScreen'))

export const CustomerProjectsScreen = lazy(() => import('./CustomerProjectsScreen'))
export const CustomerProjectDetailScreen = lazy(() => import('./CustomerProjectDetailScreen'))
export const NotificationCenterScreen = lazy(() => import('./NotificationCenterScreen'))
export const ProjectBuilderScreen = lazy(() => import('./ProjectBuilderScreen'))
export const CraftsmanOnboardingProfileScreen = lazy(() => import('./CraftsmanOnboardingProfileScreen'))
export const WorkerOnboardingScreen = lazy(() => import('./WorkerOnboardingScreen'))
export const CraftsmanOnboardingSuccessScreen = lazy(() => import('./CraftsmanOnboardingSuccessScreen'))
export const CustomerSearchScreen = lazy(() => import('./SearchScreen'))
export const CraftsmanProfile = lazy(() => import('./CraftsmanProfile'))
export const PayoutSetupScreen = lazy(() => import('./PayoutSetupScreen'))
export const PayoutReturnScreen = lazy(() => import('./PayoutReturnScreen'))
export const LegalScreen = lazy(() => import('./LegalScreen'))
export const QuoteDetailScreen = lazy(() => import('./QuoteDetailScreen'))
export const FundingEntryScreen = lazy(() => import('./FundingEntryScreen'))
export const SupplementaryFundingScreen = lazy(() => import('./SupplementaryFundingScreen'))
export const ProjectScanScreen = lazy(() => import('./ProjectScanScreen'))
