import type { ProjectTimelineEventType } from '../timeline'
import type { ReactionCategory } from './types'

/**
 * Maps every known timeline event type to a reaction category.
 * This is the single authoritative source that tells the reaction bridge
 * which category a signal belongs to, enabling per-category subscriptions.
 */
export const REACTION_CATEGORY_MAP: Record<ProjectTimelineEventType, ReactionCategory> = {
  job_created:         'job',
  work_started:        'job',
  execution_started:   'job',
  execution_completed: 'job',
  job_completed:       'job',
  waiting_payment:     'payment',
  invoice_created:     'payment',
  invoice_issued:      'payment',
  invoice_sent:        'payment',
  invoice_cancelled:   'payment',
  invoice_credit_note_issued: 'payment',
  offer_sent:          'job',
  offer_accepted:      'job',
  deposit_paid:        'payment',
  escrow_locked:       'payment',
  release_requested:   'payment',
  payment_released:    'payment',
  payment_refunded:    'payment',
  dispute_opened:      'dispute',
  dispute_resolved:    'dispute',
  dispute_resolved_release: 'dispute',
  dispute_resolved_refund:  'dispute',
  dispute_resolved_split:   'dispute',
  dispute_default_refund_applied: 'dispute',
  dispute_rejected:         'dispute',
  dispute_under_review: 'dispute',
  dispute_evidence_requested: 'dispute',
  scheduled:           'scheduling',
  job_scheduled:       'scheduling',
  schedule_updated:    'scheduling',
  schedule_confirmed:  'scheduling',
  schedule_rescheduled: 'scheduling',
  schedule_cancelled:  'scheduling',
  photo_added:         'media',
  artifact_attached:   'media',
  dispute_evidence_attached: 'dispute',
  proposal_sent:       'job',
  proposal_accepted:   'job',
  execution_ready:     'job',
  work_completed:      'job',
  funding_requested:   'payment',
  tranche_25_eligible: 'payment',
  tranche_75_eligible: 'payment',
  tranche_released: 'payment',
  release_blocked: 'payment',
  payout_handoff_initiated: 'payment',
  payout_handoff_failed: 'payment',
  payout_completed: 'payment',
  payout_failed: 'payment',
  transfer_reversed: 'payment',
  change_order_sent: 'job',
  change_order_accepted: 'job',
  change_order_declined: 'job',
  change_order_cancelled: 'job',
  supplementary_payment_required: 'payment',
  supplementary_acknowledged: 'payment',
  supplementary_funding_initiated: 'payment',
  supplementary_funded: 'payment',
  supplementary_released: 'payment',
  supplementary_paid: 'payment',
  supplementary_waived: 'payment',
  worker_marked_complete: 'job',
  admin_confirmed_complete: 'job',
  admin_rejected_completion: 'job',
  acceptance_reminder_24h: 'job',
  acceptance_reminder_60h: 'job',
  acceptance_customer_released: 'payment',
  acceptance_auto_released: 'payment',
  correction_created: 'job',
  correction_resolved: 'job',
  correction_rejected: 'job',
  presales_converted: 'job',
  spatial_shared_with_customer: 'job',
}
