import type { Invoice } from './types'

export const mockInvoices: Invoice[] = [
  {
    id: 'inv_1',
    jobId: 'job-4',
    invoiceNumber: 'FX-2026-0001',
    status: 'issued',
    parties: {
      issuerName: 'SaFix Partnerbetrieb',
      issuerAddress: 'Handwerkerstraße 12, 80331 München',
      customerName: 'Julia Neumann',
    },
    lineItems: [
      {
        id: 'li_1',
        label: 'Heizkörper entlüften & prüfen',
        quantity: 1,
        unitPrice: 243.70,
        total: 243.70,
      },
    ],
    amounts: {
      netAmount: 243.70,
      taxAmount: 46.30,
      grossAmount: 290.0,
    },
    issuedAt: Date.now() - 86_400_000,
    issuedAtLabel: 'Gestern',
    dueAtLabel: 'In 7 Tagen',
    sentAt: 0,
    servicePeriod: null,
    taxBreakdown: null,
    taxNote: null,
    providerSnapshot: null,
    customerSnapshot: null,
    sourceOfferId: null,
    sourceChangeOrderIds: [],
    sourceSupplementaryPaymentIds: [],
    kind: 'invoice',
    originalInvoiceId: null,
    correctionReason: null,
    correctionAmountCents: null,
    originalInvoiceNumber: null,
    originalInvoiceIssuedAtLabel: null,
    refundEventId: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'inv_2',
    jobId: 'job-5',
    invoiceNumber: 'FX-2026-0002',
    status: 'paid',
    parties: {
      issuerName: 'SaFix Partnerbetrieb',
      issuerAddress: 'Handwerkerstraße 12, 80331 München',
      customerName: 'Daniel Wolf',
    },
    lineItems: [
      {
        id: 'li_2',
        label: 'Steckdosen nachrüsten',
        quantity: 1,
        unitPrice: 428.57,
        total: 428.57,
      },
    ],
    amounts: {
      netAmount: 428.57,
      taxAmount: 81.43,
      grossAmount: 510.0,
    },
    issuedAt: Date.now() - 172_800_000,
    issuedAtLabel: 'Montag',
    dueAtLabel: 'Bezahlt',
    sentAt: Date.now() - 86_400_000,
    servicePeriod: null,
    taxBreakdown: null,
    taxNote: null,
    providerSnapshot: null,
    customerSnapshot: null,
    sourceOfferId: null,
    sourceChangeOrderIds: [],
    sourceSupplementaryPaymentIds: [],
    kind: 'invoice',
    originalInvoiceId: null,
    correctionReason: null,
    correctionAmountCents: null,
    originalInvoiceNumber: null,
    originalInvoiceIssuedAtLabel: null,
    refundEventId: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
]
