import type { Project } from './projectTypes'

const now = Date.now()

export const projectsMock: Project[] = [
  {
    id: 'builder_proj_demo_1',
    sourceJobId: '',
    title: 'Badezimmer modernisieren',
    customer: 'Leon',
    craftsman: '',
    location: 'Hamburg',
    dateLabel: 'Termin offen',
    price: '',
    status: 'request',
    paymentState: 'none',
    messageCount: 0,
    noteCount: 0,
    photoCount: 0,
    createdAt: now - 1000 * 60 * 60 * 24 * 1,
    updatedAt: now - 1000 * 60 * 60 * 1,
    source: 'builder',
    category: 'Badezimmer',
    description:
      'Komplette Modernisierung des Hauptbads: neue Fliesen, Dusche, Waschtisch und Spiegel.',
    requestedBudget: '6.000–9.000 €',
    requestedTiming: 'Innerhalb 8 Wochen',
  },
  {
    id: 'project-1',
    sourceJobId: 'job-1',
    title: 'Badsanierung – Leitungen prüfen',
    customer: 'Max Mustermann',
    craftsman: 'SaFix Partnerbetrieb',
    location: 'Hannover-Linden',
    dateLabel: 'Heute, 14:00 Uhr',
    price: '2.300 €',
    status: 'in_progress',
    paymentState: 'in_escrow',
    messageCount: 2,
    noteCount: 1,
    photoCount: 2,
    createdAt: now - 1000 * 60 * 60 * 24 * 5,
    updatedAt: now - 1000 * 60 * 30,
  },
  {
    id: 'project-2',
    sourceJobId: 'job-2',
    title: 'Sicherungskasten austauschen',
    customer: 'Anna Becker',
    craftsman: 'SaFix Partnerbetrieb',
    location: 'Hannover-Mitte',
    dateLabel: 'Morgen, 09:30 Uhr',
    price: '1.180 €',
    status: 'scheduled',
    paymentState: 'deposit_required',
    messageCount: 1,
    noteCount: 0,
    photoCount: 0,
    createdAt: now - 1000 * 60 * 60 * 24 * 4,
    updatedAt: now - 1000 * 60 * 60 * 8,
  },
  {
    id: 'project-3',
    sourceJobId: 'job-3',
    title: 'Wasseranschluss Küche',
    customer: 'Tobias Klein',
    craftsman: 'SaFix Partnerbetrieb',
    location: 'Hannover-Nordstadt',
    dateLabel: 'Anfrage neu',
    price: '640 €',
    status: 'request',
    paymentState: 'none',
    messageCount: 0,
    noteCount: 0,
    photoCount: 0,
    createdAt: now - 1000 * 60 * 60 * 24 * 2,
    updatedAt: now - 1000 * 60 * 60 * 2,
  },
  {
    id: 'project-4',
    sourceJobId: 'job-4',
    title: 'Heizkörper entlüften & prüfen',
    customer: 'Julia Neumann',
    craftsman: 'SaFix Partnerbetrieb',
    location: 'Hannover-Südstadt',
    dateLabel: 'Gestern abgeschlossen',
    price: '290 €',
    status: 'review',
    paymentState: 'release_pending',
    messageCount: 1,
    noteCount: 1,
    photoCount: 1,
    createdAt: now - 1000 * 60 * 60 * 24 * 3,
    updatedAt: now - 1000 * 60 * 60 * 12,
  },
  {
    id: 'project-5',
    sourceJobId: 'job-5',
    title: 'Steckdosen nachrüsten',
    customer: 'Daniel Wolf',
    craftsman: 'SaFix Partnerbetrieb',
    location: 'Hannover-List',
    dateLabel: 'Abgeschlossen',
    price: '510 €',
    status: 'completed',
    paymentState: 'released',
    messageCount: 2,
    noteCount: 1,
    photoCount: 3,
    createdAt: now - 1000 * 60 * 60 * 24 * 8,
    updatedAt: now - 1000 * 60 * 60 * 24,
  },
]
