-- Spatial Canonical · Phase 1 · Asset catalog seed (Day 19)
--
-- 36 V1 catalog assets (asset-source-map.md · 10 sanitary + 8 kitchen +
-- 8 architecture + 10 furniture). GENERATED FILE — do not hand-edit.
-- Regenerate after catalog changes:
--   npx tsx scripts/generate-spatial-catalog-seeds.ts
--
-- Source of truth: src/lib/spatial/canonical/catalog/asset-catalog.ts
-- Pairs with schema migration 20260520120012_spatial_catalog_phase1_columns.sql.
-- geometry_kind='procedural' rows (26) have NULL gltf_storage_path — their mesh
-- is built in L1 (procedural-assets.ts). geometry_kind='glb' rows (10 furniture)
-- reference real Polyhaven CC0 GLB binaries fetched via the asset manifest.
-- Idempotent: upserts on slug.

INSERT INTO public.spatial_assets (
  slug, display_name, category, object_category, geometry_kind, gltf_storage_path, thumbnail_storage_path, tags, license, attribution, vendor, published, metadata
) VALUES
  ('sanitary-toilet-standard-floor', 'Stand-WC', 'sanitary', 'toilet', 'procedural', NULL, NULL, ARRAY['wc', 'toilette', 'toilet', 'klo', 'stand']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.37,"depth_m":0.7,"height_m":0.63},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":36,"lod_levels":null}'::jsonb),
  ('sanitary-toilet-wall-hung', 'Wand-WC', 'sanitary', 'toilet', 'procedural', NULL, NULL, ARRAY['wc', 'toilette', 'toilet', 'wandhängend', 'wall hung']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.37,"depth_m":0.56,"height_m":0.705},"pivot":"wall_back_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":24,"lod_levels":null}'::jsonb),
  ('sanitary-sink-pedestal-classic', 'Standwaschbecken', 'sanitary', 'sink', 'procedural', NULL, NULL, ARRAY['waschbecken', 'sink', 'becken', 'standsäule', 'pedestal']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.5,"depth_m":0.42,"height_m":0.91},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":0.85},"polycount_lod0":140,"lod_levels":null}'::jsonb),
  ('sanitary-sink-vanity-rectangle', 'Waschtisch mit Unterschrank', 'sanitary', 'sink', 'procedural', NULL, NULL, ARRAY['waschtisch', 'waschbecken', 'sink', 'vanity', 'unterschrank']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.64,"depth_m":0.48,"height_m":0.82},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":0.85},"polycount_lod0":84,"lod_levels":null}'::jsonb),
  ('sanitary-sink-double-vanity', 'Doppelwaschtisch', 'sanitary', 'sink', 'procedural', NULL, NULL, ARRAY['waschtisch', 'doppel', 'double', 'vanity', 'sink']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":1.24,"depth_m":0.5,"height_m":0.82},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":0.85},"polycount_lod0":144,"lod_levels":null}'::jsonb),
  ('sanitary-bathtub-freestanding-oval', 'Freistehende Badewanne', 'sanitary', 'bathtub', 'procedural', NULL, NULL, ARRAY['badewanne', 'wanne', 'bathtub', 'freistehend', 'oval']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":1.7,"depth_m":0.75,"height_m":0.58},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":60,"lod_levels":null}'::jsonb),
  ('sanitary-bathtub-builtin-rectangle', 'Einbau-Badewanne', 'sanitary', 'bathtub', 'procedural', NULL, NULL, ARRAY['badewanne', 'wanne', 'bathtub', 'einbau', 'builtin']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":1.7,"depth_m":0.75,"height_m":0.56},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":60,"lod_levels":null}'::jsonb),
  ('sanitary-shower-walkin-corner', 'Eck-Walk-in-Dusche', 'sanitary', 'shower', 'procedural', NULL, NULL, ARRAY['dusche', 'shower', 'walk-in', 'ecke', 'corner']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.9,"depth_m":0.9,"height_m":2},"pivot":"corner_back_left","snap_rule":{"target_host":"corner","align_to_normal":true,"snap_to_corner":true,"min_distance_to_corner_m":0},"polycount_lod0":36,"lod_levels":null}'::jsonb),
  ('sanitary-shower-enclosure-square', 'Duschkabine', 'sanitary', 'shower', 'procedural', NULL, NULL, ARRAY['dusche', 'shower', 'kabine', 'enclosure', 'glas']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.9,"depth_m":0.9,"height_m":2},"pivot":"bottom_center","snap_rule":{"target_host":"corner","align_to_normal":true,"snap_to_corner":true,"min_distance_to_corner_m":0},"polycount_lod0":48,"lod_levels":null}'::jsonb),
  ('sanitary-bidet-floor-standing', 'Stand-Bidet', 'sanitary', 'bidet', 'procedural', NULL, NULL, ARRAY['bidet', 'stand']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.36,"depth_m":0.5,"height_m":0.4},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":72,"lod_levels":null}'::jsonb),
  ('kitchen-sink-undermount-double', 'Unterbau-Spüle (Doppelbecken)', 'kitchen', 'kitchen_sink', 'procedural', NULL, NULL, ARRAY['spüle', 'sink', 'becken', 'unterbau', 'doppel']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.9,"depth_m":0.6,"height_m":0.24},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":0.9},"polycount_lod0":132,"lod_levels":null}'::jsonb),
  ('kitchen-stove-induction-60cm', 'Induktionskochfeld 60 cm', 'kitchen', 'cooktop', 'procedural', NULL, NULL, ARRAY['kochfeld', 'herd', 'cooktop', 'induktion', 'stove']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.6,"depth_m":0.52,"height_m":0.056},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":332,"lod_levels":null}'::jsonb),
  ('kitchen-oven-builtin-60cm', 'Einbau-Backofen 60 cm', 'kitchen', 'oven', 'procedural', NULL, NULL, ARRAY['backofen', 'ofen', 'oven', 'einbau']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.6,"depth_m":0.645,"height_m":0.6},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":0.6},"polycount_lod0":36,"lod_levels":null}'::jsonb),
  ('kitchen-refrigerator-freestanding-tall', 'Standkühlschrank', 'kitchen', 'refrigerator', 'procedural', NULL, NULL, ARRAY['kühlschrank', 'fridge', 'refrigerator', 'kühl']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.7,"depth_m":0.76,"height_m":1.85},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":48,"lod_levels":null}'::jsonb),
  ('kitchen-dishwasher-builtin-60cm', 'Einbau-Geschirrspüler 60 cm', 'kitchen', 'dishwasher', 'procedural', NULL, NULL, ARRAY['geschirrspüler', 'spülmaschine', 'dishwasher', 'einbau']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.6,"depth_m":0.64,"height_m":0.82},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":36,"lod_levels":null}'::jsonb),
  ('kitchen-extractor-hood-wall-mounted', 'Wand-Dunstabzugshaube', 'kitchen', 'range_hood', 'procedural', NULL, NULL, ARRAY['dunstabzug', 'haube', 'hood', 'abzug']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.6,"depth_m":0.49,"height_m":0.68},"pivot":"wall_back_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":1.5},"polycount_lod0":24,"lod_levels":null}'::jsonb),
  ('kitchen-microwave-countertop', 'Mikrowelle', 'kitchen', 'oven', 'procedural', NULL, NULL, ARRAY['mikrowelle', 'microwave']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.5,"depth_m":0.405,"height_m":0.3},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":0.6},"polycount_lod0":36,"lod_levels":null}'::jsonb),
  ('kitchen-faucet-pullout-tall', 'Küchenarmatur mit Auszug', 'kitchen', 'kitchen_faucet', 'procedural', NULL, NULL, ARRAY['armatur', 'wasserhahn', 'faucet', 'hahn', 'auszug']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.08,"depth_m":0.19,"height_m":0.405},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":1.02},"polycount_lod0":172,"lod_levels":null}'::jsonb),
  ('arch-door-single-leaf-standard', 'Innentür einflügelig', 'architecture', NULL, 'procedural', NULL, NULL, ARRAY['tür', 'door', 'innentür', 'einflügelig']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.96,"depth_m":0.145,"height_m":2.1},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true},"polycount_lod0":60,"lod_levels":null}'::jsonb),
  ('arch-door-double-french', 'Doppeltür (französisch)', 'architecture', NULL, 'procedural', NULL, NULL, ARRAY['tür', 'door', 'doppeltür', 'french', 'französisch']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":1.62,"depth_m":0.145,"height_m":2.1},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true},"polycount_lod0":84,"lod_levels":null}'::jsonb),
  ('arch-window-double-hung-standard', 'Schiebefenster', 'architecture', NULL, 'procedural', NULL, NULL, ARRAY['fenster', 'window', 'schiebefenster', 'double hung']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":1.2,"depth_m":0.12,"height_m":1.4},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true},"polycount_lod0":72,"lod_levels":null}'::jsonb),
  ('arch-window-casement-2-pane', 'Drehflügelfenster (2-flügelig)', 'architecture', NULL, 'procedural', NULL, NULL, ARRAY['fenster', 'window', 'drehflügel', 'casement']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":1.2,"depth_m":0.12,"height_m":1.4},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true},"polycount_lod0":84,"lod_levels":null}'::jsonb),
  ('arch-radiator-panel-wall', 'Flachheizkörper', 'architecture', 'radiator', 'procedural', NULL, NULL, ARRAY['heizkörper', 'heizung', 'radiator', 'flach']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.8,"depth_m":0.1,"height_m":0.6},"pivot":"wall_back_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":0.12},"polycount_lod0":120,"lod_levels":null}'::jsonb),
  ('arch-radiator-towel-bath', 'Handtuchheizkörper', 'architecture', 'radiator', 'procedural', NULL, NULL, ARRAY['heizkörper', 'handtuchheizung', 'radiator', 'towel', 'bad']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.5,"depth_m":0.06,"height_m":1.1},"pivot":"wall_back_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":0.12},"polycount_lod0":120,"lod_levels":null}'::jsonb),
  ('arch-outlet-socket-double', 'Doppelsteckdose', 'architecture', 'electrical_outlet', 'procedural', NULL, NULL, ARRAY['steckdose', 'outlet', 'socket', 'strom', 'doppel']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.16,"depth_m":0.056,"height_m":0.09},"pivot":"wall_back_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":0.3},"polycount_lod0":172,"lod_levels":null}'::jsonb),
  ('arch-light-switch-single', 'Lichtschalter', 'architecture', 'light_switch', 'procedural', NULL, NULL, ARRAY['schalter', 'lichtschalter', 'switch', 'licht']::text[], 'CC0-1.0', NULL, 'procedural', true, '{"dimensions":{"width_m":0.08,"depth_m":0.02,"height_m":0.08},"pivot":"wall_back_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":1.05},"polycount_lod0":24,"lod_levels":null}'::jsonb),
  ('furn-sofa-3seater-fabric-grey', '3-Sitzer-Sofa', 'furniture', 'sofa', 'glb', 'spatial-assets/models/furn-sofa-3seater-fabric-grey.glb', 'spatial-assets/thumbnails/furn-sofa-3seater-fabric-grey.jpg', ARRAY['sofa', 'couch', 'sitzgelegenheit', '3-sitzer']::text[], 'CC0-1.0', NULL, 'polyhaven', true, '{"dimensions":{"width_m":2.1,"depth_m":0.92,"height_m":0.85},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":12000,"lod_levels":[{"level":0,"glb_url":"spatial-assets/models/furn-sofa-3seater-fabric-grey.glb","poly_count":12000,"distance_m_max":2},{"level":1,"glb_url":"spatial-assets/models/furn-sofa-3seater-fabric-grey-lod1.glb","poly_count":3000,"distance_m_max":8},{"level":2,"glb_url":"spatial-assets/models/furn-sofa-3seater-fabric-grey-lod2.glb","poly_count":960,"distance_m_max":1000000}]}'::jsonb),
  ('furn-armchair-fabric-rounded', 'Sessel', 'furniture', 'armchair', 'glb', 'spatial-assets/models/furn-armchair-fabric-rounded.glb', 'spatial-assets/thumbnails/furn-armchair-fabric-rounded.jpg', ARRAY['sessel', 'armchair', 'stuhl']::text[], 'CC0-1.0', NULL, 'polyhaven', true, '{"dimensions":{"width_m":0.85,"depth_m":0.85,"height_m":0.95},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":8000,"lod_levels":[{"level":0,"glb_url":"spatial-assets/models/furn-armchair-fabric-rounded.glb","poly_count":8000,"distance_m_max":2},{"level":1,"glb_url":"spatial-assets/models/furn-armchair-fabric-rounded-lod1.glb","poly_count":2000,"distance_m_max":8},{"level":2,"glb_url":"spatial-assets/models/furn-armchair-fabric-rounded-lod2.glb","poly_count":640,"distance_m_max":1000000}]}'::jsonb),
  ('furn-coffee-table-round-wood', 'Couchtisch rund', 'furniture', 'table', 'glb', 'spatial-assets/models/furn-coffee-table-round-wood.glb', 'spatial-assets/thumbnails/furn-coffee-table-round-wood.jpg', ARRAY['couchtisch', 'tisch', 'table', 'rund']::text[], 'CC0-1.0', NULL, 'polyhaven', true, '{"dimensions":{"width_m":0.9,"depth_m":0.9,"height_m":0.42},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":4000,"lod_levels":[{"level":0,"glb_url":"spatial-assets/models/furn-coffee-table-round-wood.glb","poly_count":4000,"distance_m_max":2},{"level":1,"glb_url":"spatial-assets/models/furn-coffee-table-round-wood-lod1.glb","poly_count":1000,"distance_m_max":8},{"level":2,"glb_url":"spatial-assets/models/furn-coffee-table-round-wood-lod2.glb","poly_count":320,"distance_m_max":1000000}]}'::jsonb),
  ('furn-dining-table-rectangle-6', 'Esstisch (6 Personen)', 'furniture', 'table', 'glb', 'spatial-assets/models/furn-dining-table-rectangle-6.glb', 'spatial-assets/thumbnails/furn-dining-table-rectangle-6.jpg', ARRAY['esstisch', 'tisch', 'table', 'dining']::text[], 'CC0-1.0', NULL, 'polyhaven', true, '{"dimensions":{"width_m":1.8,"depth_m":0.9,"height_m":0.75},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":6000,"lod_levels":[{"level":0,"glb_url":"spatial-assets/models/furn-dining-table-rectangle-6.glb","poly_count":6000,"distance_m_max":2},{"level":1,"glb_url":"spatial-assets/models/furn-dining-table-rectangle-6-lod1.glb","poly_count":1500,"distance_m_max":8},{"level":2,"glb_url":"spatial-assets/models/furn-dining-table-rectangle-6-lod2.glb","poly_count":480,"distance_m_max":1000000}]}'::jsonb),
  ('furn-dining-chair-wood-fabric', 'Esszimmerstuhl', 'furniture', 'chair', 'glb', 'spatial-assets/models/furn-dining-chair-wood-fabric.glb', 'spatial-assets/thumbnails/furn-dining-chair-wood-fabric.jpg', ARRAY['stuhl', 'chair', 'esszimmerstuhl']::text[], 'CC0-1.0', NULL, 'polyhaven', true, '{"dimensions":{"width_m":0.46,"depth_m":0.52,"height_m":0.9},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":4000,"lod_levels":[{"level":0,"glb_url":"spatial-assets/models/furn-dining-chair-wood-fabric.glb","poly_count":4000,"distance_m_max":2},{"level":1,"glb_url":"spatial-assets/models/furn-dining-chair-wood-fabric-lod1.glb","poly_count":1000,"distance_m_max":8},{"level":2,"glb_url":"spatial-assets/models/furn-dining-chair-wood-fabric-lod2.glb","poly_count":320,"distance_m_max":1000000}]}'::jsonb),
  ('furn-bed-double-frame-headboard', 'Doppelbett mit Kopfteil', 'furniture', 'bed', 'glb', 'spatial-assets/models/furn-bed-double-frame-headboard.glb', 'spatial-assets/thumbnails/furn-bed-double-frame-headboard.jpg', ARRAY['bett', 'bed', 'doppelbett']::text[], 'CC0-1.0', NULL, 'polyhaven', true, '{"dimensions":{"width_m":1.6,"depth_m":2.1,"height_m":1},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":10000,"lod_levels":[{"level":0,"glb_url":"spatial-assets/models/furn-bed-double-frame-headboard.glb","poly_count":10000,"distance_m_max":2},{"level":1,"glb_url":"spatial-assets/models/furn-bed-double-frame-headboard-lod1.glb","poly_count":2500,"distance_m_max":8},{"level":2,"glb_url":"spatial-assets/models/furn-bed-double-frame-headboard-lod2.glb","poly_count":800,"distance_m_max":1000000}]}'::jsonb),
  ('furn-wardrobe-3door-tall', 'Kleiderschrank 3-türig', 'furniture', 'wardrobe', 'glb', 'spatial-assets/models/furn-wardrobe-3door-tall.glb', 'spatial-assets/thumbnails/furn-wardrobe-3door-tall.jpg', ARRAY['schrank', 'kleiderschrank', 'wardrobe']::text[], 'CC0-1.0', NULL, 'polyhaven', true, '{"dimensions":{"width_m":1.5,"depth_m":0.6,"height_m":2.1},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":5000,"lod_levels":[{"level":0,"glb_url":"spatial-assets/models/furn-wardrobe-3door-tall.glb","poly_count":5000,"distance_m_max":2},{"level":1,"glb_url":"spatial-assets/models/furn-wardrobe-3door-tall-lod1.glb","poly_count":1250,"distance_m_max":8},{"level":2,"glb_url":"spatial-assets/models/furn-wardrobe-3door-tall-lod2.glb","poly_count":400,"distance_m_max":1000000}]}'::jsonb),
  ('furn-shelf-open-5tier-wood', 'Offenes Regal 5 Böden', 'furniture', 'bookshelf', 'glb', 'spatial-assets/models/furn-shelf-open-5tier-wood.glb', 'spatial-assets/thumbnails/furn-shelf-open-5tier-wood.jpg', ARRAY['regal', 'shelf', 'bücherregal', 'bookshelf']::text[], 'CC0-1.0', NULL, 'polyhaven', true, '{"dimensions":{"width_m":0.9,"depth_m":0.35,"height_m":1.8},"pivot":"bottom_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":1},"polycount_lod0":4000,"lod_levels":[{"level":0,"glb_url":"spatial-assets/models/furn-shelf-open-5tier-wood.glb","poly_count":4000,"distance_m_max":2},{"level":1,"glb_url":"spatial-assets/models/furn-shelf-open-5tier-wood-lod1.glb","poly_count":1000,"distance_m_max":8},{"level":2,"glb_url":"spatial-assets/models/furn-shelf-open-5tier-wood-lod2.glb","poly_count":320,"distance_m_max":1000000}]}'::jsonb),
  ('furn-mirror-round-wall', 'Wandspiegel rund', 'furniture', 'mirror', 'glb', 'spatial-assets/models/furn-mirror-round-wall.glb', 'spatial-assets/thumbnails/furn-mirror-round-wall.jpg', ARRAY['spiegel', 'mirror', 'wandspiegel', 'rund']::text[], 'CC0-1.0', NULL, 'polyhaven', true, '{"dimensions":{"width_m":0.8,"depth_m":0.05,"height_m":0.8},"pivot":"wall_back_center","snap_rule":{"target_host":"wall","align_to_normal":true,"default_height_from_floor_m":1.35},"polycount_lod0":1000,"lod_levels":[{"level":0,"glb_url":"spatial-assets/models/furn-mirror-round-wall.glb","poly_count":1000,"distance_m_max":2},{"level":1,"glb_url":"spatial-assets/models/furn-mirror-round-wall-lod1.glb","poly_count":250,"distance_m_max":8},{"level":2,"glb_url":"spatial-assets/models/furn-mirror-round-wall-lod2.glb","poly_count":80,"distance_m_max":1000000}]}'::jsonb),
  ('furn-floor-lamp-tripod', 'Stehlampe Tripod', 'furniture', 'lamp', 'glb', 'spatial-assets/models/furn-floor-lamp-tripod.glb', 'spatial-assets/thumbnails/furn-floor-lamp-tripod.jpg', ARRAY['lampe', 'stehlampe', 'lamp', 'tripod', 'licht']::text[], 'CC0-1.0', NULL, 'polyhaven', true, '{"dimensions":{"width_m":0.5,"depth_m":0.5,"height_m":1.6},"pivot":"bottom_center","snap_rule":{"target_host":"floor","align_to_normal":false,"min_distance_to_corner_m":0.05},"polycount_lod0":3000,"lod_levels":[{"level":0,"glb_url":"spatial-assets/models/furn-floor-lamp-tripod.glb","poly_count":3000,"distance_m_max":2},{"level":1,"glb_url":"spatial-assets/models/furn-floor-lamp-tripod-lod1.glb","poly_count":750,"distance_m_max":8},{"level":2,"glb_url":"spatial-assets/models/furn-floor-lamp-tripod-lod2.glb","poly_count":240,"distance_m_max":1000000}]}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  category = EXCLUDED.category,
  object_category = EXCLUDED.object_category,
  geometry_kind = EXCLUDED.geometry_kind,
  gltf_storage_path = EXCLUDED.gltf_storage_path,
  thumbnail_storage_path = EXCLUDED.thumbnail_storage_path,
  tags = EXCLUDED.tags,
  license = EXCLUDED.license,
  attribution = EXCLUDED.attribution,
  vendor = EXCLUDED.vendor,
  published = EXCLUDED.published,
  metadata = EXCLUDED.metadata,
  updated_at = now();
