-- ============================================================
-- Schema / Code Sync Alignment
-- ============================================================
-- Aligns repo migration state with the live-applied Supabase schema.
--
-- Drift identified:
--   1. jobs.source_offer_id was TEXT — live schema uses UUID
--   2. funding_requests.conversation_id was TEXT — live schema uses UUID
--   3. funding_requests lacks provider_id — live schema includes it
--   4. funding_requests_customer_update RLS policy exists in migrations
--      but live RLS is customer read-only (provider insert/read/update,
--      service all)
--
-- This follow-up migration corrects all four drifts so that future
-- environments built from the repo produce the same schema as live.
-- ============================================================

-- ── 1. jobs.source_offer_id: TEXT → UUID ──────────────────────────────────
-- The escrow_payment_plans and funding_requests tables already define
-- source_offer_id as UUID. Aligning the jobs column removes the type
-- mismatch. Existing TEXT values are valid UUID strings (generated by
-- gen_random_uuid / crypto.randomUUID).

ALTER TABLE public.jobs
  ALTER COLUMN source_offer_id TYPE uuid USING source_offer_id::uuid;

-- ── 2. funding_requests.conversation_id: TEXT → UUID ──────────────────────
-- Conversation IDs are Supabase-generated UUIDs. Aligning the column
-- type to UUID enforces referential correctness.

ALTER TABLE funding_requests
  ALTER COLUMN conversation_id TYPE uuid USING conversation_id::uuid;

-- ── 3. funding_requests: add provider_id column ──────────────────────────
-- The live schema includes both provider_id (canonical providers.id FK)
-- and provider_user_id (auth user ID). The base migration only created
-- provider_user_id. Adding provider_id brings the repo in line with live.

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'funding_requests' AND column_name = 'provider_id'
  ) THEN
    ALTER TABLE funding_requests ADD COLUMN provider_id UUID;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_funding_requests_provider_id
  ON funding_requests (provider_id)
  WHERE provider_id IS NOT NULL;

-- ── 4. Drop customer UPDATE policy on funding_requests ────────────────────
-- The live RLS is:
--   • customer: SELECT only
--   • provider: SELECT, INSERT, UPDATE
--   • service_role: ALL
--
-- Migration 20260325000004 added a funding_requests_customer_update policy
-- that is NOT present in the live schema. Dropping it aligns the repo
-- with the actual live RLS.

DROP POLICY IF EXISTS funding_requests_customer_update ON funding_requests;
