-- Spatial Canonical · Phase 1 · Material catalog seed (Day 20)
--
-- 32 verified ambientCG CC0 PBR materials (spatial-v1-material-curation.md).
-- GENERATED FILE — do not hand-edit. Regenerate after catalog changes:
--   npx tsx scripts/generate-spatial-catalog-seeds.ts
--
-- Source of truth: src/lib/spatial/canonical/catalog/material-catalog.ts
-- Pairs with schema migration 20260520120012_spatial_catalog_phase1_columns.sql.
-- Idempotent: upserts on slug. Texture paths point at Supabase Storage; the
-- binaries are fetched separately (see scripts/download-spatial-assets.sh).

INSERT INTO public.spatial_materials (
  slug, display_name, category, surface_category, section, albedo_path, normal_path, roughness_path, metallic_path, ao_path, displacement_path, tile_scale_u_m, tile_scale_v_m, tags, is_procedural, license, attribution, vendor, published, metadata
) VALUES
  ('wall-paint-white', 'Paint White', 'paint', 'wall', 'Farbe & Putz', 'spatial-assets/materials/wall-paint-white/albedo.ktx2', 'spatial-assets/materials/wall-paint-white/normal.ktx2', 'spatial-assets/materials/wall-paint-white/roughness.ktx2', NULL, 'spatial-assets/materials/wall-paint-white/ao.ktx2', 'spatial-assets/materials/wall-paint-white/displacement.ktx2', 4, 4, ARRAY['weiß', 'white', 'farbe', 'paint', 'matt']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Plaster001","roughness":0.9,"metalness":0,"fallback_color_hex":"#F2F1ED","thumbnail_path":"spatial-assets/materials/thumbnails/wall-paint-white.jpg"}'::jsonb),
  ('wall-plaster-creme', 'Putz Creme', 'plaster', 'wall', 'Farbe & Putz', 'spatial-assets/materials/wall-plaster-creme/albedo.ktx2', 'spatial-assets/materials/wall-plaster-creme/normal.ktx2', 'spatial-assets/materials/wall-plaster-creme/roughness.ktx2', NULL, 'spatial-assets/materials/wall-plaster-creme/ao.ktx2', 'spatial-assets/materials/wall-plaster-creme/displacement.ktx2', 4, 4, ARRAY['creme', 'cream', 'putz', 'plaster', 'beige']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Plaster002","roughness":0.9,"metalness":0,"fallback_color_hex":"#E8E0D2","thumbnail_path":"spatial-assets/materials/thumbnails/wall-plaster-creme.jpg"}'::jsonb),
  ('wall-plaster-struktur', 'Putz Struktur', 'plaster', 'wall', 'Farbe & Putz', 'spatial-assets/materials/wall-plaster-struktur/albedo.ktx2', 'spatial-assets/materials/wall-plaster-struktur/normal.ktx2', 'spatial-assets/materials/wall-plaster-struktur/roughness.ktx2', NULL, 'spatial-assets/materials/wall-plaster-struktur/ao.ktx2', 'spatial-assets/materials/wall-plaster-struktur/displacement.ktx2', 3, 3, ARRAY['struktur', 'textured', 'putz', 'plaster', 'rau']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Plaster003","roughness":0.9,"metalness":0,"fallback_color_hex":"#DAD4C8","thumbnail_path":"spatial-assets/materials/thumbnails/wall-plaster-struktur.jpg"}'::jsonb),
  ('wall-tile-white', 'Wandfliese Weiß', 'tile', 'wall', 'Fliesen', 'spatial-assets/materials/wall-tile-white/albedo.ktx2', 'spatial-assets/materials/wall-tile-white/normal.ktx2', 'spatial-assets/materials/wall-tile-white/roughness.ktx2', NULL, 'spatial-assets/materials/wall-tile-white/ao.ktx2', 'spatial-assets/materials/wall-tile-white/displacement.ktx2', 0.3, 0.3, ARRAY['fliese', 'weiß', 'white', 'tile', 'glanz', 'glossy', 'keramik']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Tiles036","roughness":0.9,"metalness":0,"fallback_color_hex":"#F4F4F2","thumbnail_path":"spatial-assets/materials/thumbnails/wall-tile-white.jpg"}'::jsonb),
  ('wall-tile-grey', 'Fliese Grau', 'tile', 'wall', 'Fliesen', 'spatial-assets/materials/wall-tile-grey/albedo.ktx2', 'spatial-assets/materials/wall-tile-grey/normal.ktx2', 'spatial-assets/materials/wall-tile-grey/roughness.ktx2', NULL, 'spatial-assets/materials/wall-tile-grey/ao.ktx2', 'spatial-assets/materials/wall-tile-grey/displacement.ktx2', 0.3, 0.3, ARRAY['fliese', 'grau', 'grey', 'gray', 'tile']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Tiles040","roughness":0.9,"metalness":0,"fallback_color_hex":"#B8B9BA","thumbnail_path":"spatial-assets/materials/thumbnails/wall-tile-grey.jpg"}'::jsonb),
  ('wall-marble', 'Marmor-Optik', 'stone', 'wall', 'Fliesen', 'spatial-assets/materials/wall-marble/albedo.ktx2', 'spatial-assets/materials/wall-marble/normal.ktx2', 'spatial-assets/materials/wall-marble/roughness.ktx2', NULL, 'spatial-assets/materials/wall-marble/ao.ktx2', 'spatial-assets/materials/wall-marble/displacement.ktx2', 1.2, 0.6, ARRAY['marmor', 'marble', 'stein', 'stone', 'edel']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Marble012","roughness":0.9,"metalness":0,"fallback_color_hex":"#E7E6E3","thumbnail_path":"spatial-assets/materials/thumbnails/wall-marble.jpg"}'::jsonb),
  ('wall-oak', 'Eiche Vertäfelung', 'wood', 'wall', 'Holz & Tapete', 'spatial-assets/materials/wall-oak/albedo.ktx2', 'spatial-assets/materials/wall-oak/normal.ktx2', 'spatial-assets/materials/wall-oak/roughness.ktx2', NULL, 'spatial-assets/materials/wall-oak/ao.ktx2', 'spatial-assets/materials/wall-oak/displacement.ktx2', 0.2, 2.4, ARRAY['eiche', 'oak', 'holz', 'wood', 'vertäfelung']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Wood049","roughness":0.9,"metalness":0,"fallback_color_hex":"#B68F5E","thumbnail_path":"spatial-assets/materials/thumbnails/wall-oak.jpg"}'::jsonb),
  ('wall-linen', 'Leinen-Tapete', 'fabric', 'wall', 'Holz & Tapete', 'spatial-assets/materials/wall-linen/albedo.ktx2', 'spatial-assets/materials/wall-linen/normal.ktx2', 'spatial-assets/materials/wall-linen/roughness.ktx2', NULL, 'spatial-assets/materials/wall-linen/ao.ktx2', 'spatial-assets/materials/wall-linen/displacement.ktx2', 1, 1.4, ARRAY['leinen', 'linen', 'tapete', 'wallpaper', 'stoff']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Fabric062","roughness":0.9,"metalness":0,"fallback_color_hex":"#D8CFC0","thumbnail_path":"spatial-assets/materials/thumbnails/wall-linen.jpg"}'::jsonb),
  ('wall-concrete', 'Sichtbeton', 'concrete', 'wall', 'Beton & Ziegel', 'spatial-assets/materials/wall-concrete/albedo.ktx2', 'spatial-assets/materials/wall-concrete/normal.ktx2', 'spatial-assets/materials/wall-concrete/roughness.ktx2', NULL, 'spatial-assets/materials/wall-concrete/ao.ktx2', 'spatial-assets/materials/wall-concrete/displacement.ktx2', 3, 3, ARRAY['beton', 'concrete', 'sichtbeton', 'grau', 'industrial']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Concrete034","roughness":0.9,"metalness":0,"fallback_color_hex":"#9C9B98","thumbnail_path":"spatial-assets/materials/thumbnails/wall-concrete.jpg"}'::jsonb),
  ('wall-brick-white', 'Ziegel Weiß', 'brick', 'wall', 'Beton & Ziegel', 'spatial-assets/materials/wall-brick-white/albedo.ktx2', 'spatial-assets/materials/wall-brick-white/normal.ktx2', 'spatial-assets/materials/wall-brick-white/roughness.ktx2', NULL, 'spatial-assets/materials/wall-brick-white/ao.ktx2', 'spatial-assets/materials/wall-brick-white/displacement.ktx2', 2, 1.5, ARRAY['ziegel', 'brick', 'mauer', 'weiß', 'white']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Bricks060","roughness":0.9,"metalness":0,"fallback_color_hex":"#E4E1DB","thumbnail_path":"spatial-assets/materials/thumbnails/wall-brick-white.jpg"}'::jsonb),
  ('floor-oak', 'Eiche Diele', 'wood', 'floor', 'Holz', 'spatial-assets/materials/floor-oak/albedo.ktx2', 'spatial-assets/materials/floor-oak/normal.ktx2', 'spatial-assets/materials/floor-oak/roughness.ktx2', NULL, 'spatial-assets/materials/floor-oak/ao.ktx2', 'spatial-assets/materials/floor-oak/displacement.ktx2', 0.2, 1.6, ARRAY['eiche', 'oak', 'holz', 'wood', 'diele', 'parkett']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"WoodFloor051","roughness":0.9,"metalness":0,"fallback_color_hex":"#B58A5A","thumbnail_path":"spatial-assets/materials/thumbnails/floor-oak.jpg"}'::jsonb),
  ('floor-walnut', 'Walnuss Rustikal', 'wood', 'floor', 'Holz', 'spatial-assets/materials/floor-walnut/albedo.ktx2', 'spatial-assets/materials/floor-walnut/normal.ktx2', 'spatial-assets/materials/floor-walnut/roughness.ktx2', NULL, 'spatial-assets/materials/floor-walnut/ao.ktx2', 'spatial-assets/materials/floor-walnut/displacement.ktx2', 0.18, 1.4, ARRAY['walnuss', 'walnut', 'holz', 'wood', 'rustikal']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"WoodFloor043","roughness":0.9,"metalness":0,"fallback_color_hex":"#6E4A30","thumbnail_path":"spatial-assets/materials/thumbnails/floor-walnut.jpg"}'::jsonb),
  ('floor-tile-anthracite', 'Feinsteinzeug Anthrazit', 'tile', 'floor', 'Fliesen & Stein', 'spatial-assets/materials/floor-tile-anthracite/albedo.ktx2', 'spatial-assets/materials/floor-tile-anthracite/normal.ktx2', 'spatial-assets/materials/floor-tile-anthracite/roughness.ktx2', NULL, 'spatial-assets/materials/floor-tile-anthracite/ao.ktx2', 'spatial-assets/materials/floor-tile-anthracite/displacement.ktx2', 0.6, 0.6, ARRAY['fliese', 'feinsteinzeug', 'anthrazit', 'tile', 'dunkel']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Tiles052","roughness":0.9,"metalness":0,"fallback_color_hex":"#3C3D3F","thumbnail_path":"spatial-assets/materials/thumbnails/floor-tile-anthracite.jpg"}'::jsonb),
  ('floor-natural-stone', 'Naturstein-Boden', 'stone', 'floor', 'Fliesen & Stein', 'spatial-assets/materials/floor-natural-stone/albedo.ktx2', 'spatial-assets/materials/floor-natural-stone/normal.ktx2', 'spatial-assets/materials/floor-natural-stone/roughness.ktx2', NULL, 'spatial-assets/materials/floor-natural-stone/ao.ktx2', 'spatial-assets/materials/floor-natural-stone/displacement.ktx2', 0.5, 0.5, ARRAY['naturstein', 'stone', 'stein', 'boden']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Tiles093","roughness":0.9,"metalness":0,"fallback_color_hex":"#A9A296","thumbnail_path":"spatial-assets/materials/thumbnails/floor-natural-stone.jpg"}'::jsonb),
  ('floor-marble', 'Marmorboden', 'stone', 'floor', 'Fliesen & Stein', 'spatial-assets/materials/floor-marble/albedo.ktx2', 'spatial-assets/materials/floor-marble/normal.ktx2', 'spatial-assets/materials/floor-marble/roughness.ktx2', NULL, 'spatial-assets/materials/floor-marble/ao.ktx2', 'spatial-assets/materials/floor-marble/displacement.ktx2', 0.8, 0.8, ARRAY['marmor', 'marble', 'stein', 'stone', 'boden']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Marble020","roughness":0.9,"metalness":0,"fallback_color_hex":"#E5E3DF","thumbnail_path":"spatial-assets/materials/thumbnails/floor-marble.jpg"}'::jsonb),
  ('floor-slate', 'Schiefer', 'stone', 'floor', 'Fliesen & Stein', 'spatial-assets/materials/floor-slate/albedo.ktx2', 'spatial-assets/materials/floor-slate/normal.ktx2', 'spatial-assets/materials/floor-slate/roughness.ktx2', NULL, 'spatial-assets/materials/floor-slate/ao.ktx2', 'spatial-assets/materials/floor-slate/displacement.ktx2', 0.4, 0.4, ARRAY['schiefer', 'slate', 'stein', 'stone', 'dunkel']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Rock035","roughness":0.9,"metalness":0,"fallback_color_hex":"#4A4B4D","thumbnail_path":"spatial-assets/materials/thumbnails/floor-slate.jpg"}'::jsonb),
  ('floor-carpet-grey', 'Teppich Grau', 'fabric', 'floor', 'Teppich & Weich', 'spatial-assets/materials/floor-carpet-grey/albedo.ktx2', 'spatial-assets/materials/floor-carpet-grey/normal.ktx2', 'spatial-assets/materials/floor-carpet-grey/roughness.ktx2', NULL, 'spatial-assets/materials/floor-carpet-grey/ao.ktx2', 'spatial-assets/materials/floor-carpet-grey/displacement.ktx2', 4, 4, ARRAY['teppich', 'carpet', 'grau', 'grey', 'weich']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Carpet003","roughness":0.9,"metalness":0,"fallback_color_hex":"#8E8E8C","thumbnail_path":"spatial-assets/materials/thumbnails/floor-carpet-grey.jpg"}'::jsonb),
  ('floor-concrete-screed', 'Estrich Beton', 'concrete', 'floor', 'Beton & Estrich', 'spatial-assets/materials/floor-concrete-screed/albedo.ktx2', 'spatial-assets/materials/floor-concrete-screed/normal.ktx2', 'spatial-assets/materials/floor-concrete-screed/roughness.ktx2', NULL, 'spatial-assets/materials/floor-concrete-screed/ao.ktx2', 'spatial-assets/materials/floor-concrete-screed/displacement.ktx2', 4, 4, ARRAY['estrich', 'beton', 'concrete', 'screed', 'industrial']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Concrete031","roughness":0.9,"metalness":0,"fallback_color_hex":"#959492","thumbnail_path":"spatial-assets/materials/thumbnails/floor-concrete-screed.jpg"}'::jsonb),
  ('counter-marble-beige', 'Marmor Beige', 'stone', 'counter', 'Naturstein', 'spatial-assets/materials/counter-marble-beige/albedo.ktx2', 'spatial-assets/materials/counter-marble-beige/normal.ktx2', 'spatial-assets/materials/counter-marble-beige/roughness.ktx2', NULL, 'spatial-assets/materials/counter-marble-beige/ao.ktx2', 'spatial-assets/materials/counter-marble-beige/displacement.ktx2', 2.5, 0.65, ARRAY['marmor', 'marble', 'beige', 'stein', 'arbeitsplatte']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Marble014","roughness":0.9,"metalness":0,"fallback_color_hex":"#E3DACA","thumbnail_path":"spatial-assets/materials/thumbnails/counter-marble-beige.jpg"}'::jsonb),
  ('counter-granite-dark', 'Granit Dunkel', 'stone', 'counter', 'Naturstein', 'spatial-assets/materials/counter-granite-dark/albedo.ktx2', 'spatial-assets/materials/counter-granite-dark/normal.ktx2', 'spatial-assets/materials/counter-granite-dark/roughness.ktx2', NULL, 'spatial-assets/materials/counter-granite-dark/ao.ktx2', 'spatial-assets/materials/counter-granite-dark/displacement.ktx2', 2.5, 0.65, ARRAY['granit', 'granite', 'dunkel', 'stein', 'arbeitsplatte']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Rock041","roughness":0.9,"metalness":0,"fallback_color_hex":"#37373A","thumbnail_path":"spatial-assets/materials/thumbnails/counter-granite-dark.jpg"}'::jsonb),
  ('counter-quartz-white', 'Quarz Weiß', 'stone', 'counter', 'Beton & Quarz', 'spatial-assets/materials/counter-quartz-white/albedo.ktx2', 'spatial-assets/materials/counter-quartz-white/normal.ktx2', 'spatial-assets/materials/counter-quartz-white/roughness.ktx2', NULL, 'spatial-assets/materials/counter-quartz-white/ao.ktx2', 'spatial-assets/materials/counter-quartz-white/displacement.ktx2', 2.5, 0.65, ARRAY['quarz', 'quartz', 'weiß', 'white', 'arbeitsplatte']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Marble021","roughness":0.9,"metalness":0,"fallback_color_hex":"#EEEDEA","thumbnail_path":"spatial-assets/materials/thumbnails/counter-quartz-white.jpg"}'::jsonb),
  ('counter-wood-walnut', 'Holz Walnuss', 'wood', 'counter', 'Holz', 'spatial-assets/materials/counter-wood-walnut/albedo.ktx2', 'spatial-assets/materials/counter-wood-walnut/normal.ktx2', 'spatial-assets/materials/counter-wood-walnut/roughness.ktx2', NULL, 'spatial-assets/materials/counter-wood-walnut/ao.ktx2', 'spatial-assets/materials/counter-wood-walnut/displacement.ktx2', 2.5, 0.6, ARRAY['holz', 'wood', 'walnuss', 'walnut', 'arbeitsplatte']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Wood051","roughness":0.9,"metalness":0,"fallback_color_hex":"#7A553A","thumbnail_path":"spatial-assets/materials/thumbnails/counter-wood-walnut.jpg"}'::jsonb),
  ('counter-concrete-light', 'Beton Hell', 'concrete', 'counter', 'Beton & Quarz', 'spatial-assets/materials/counter-concrete-light/albedo.ktx2', 'spatial-assets/materials/counter-concrete-light/normal.ktx2', 'spatial-assets/materials/counter-concrete-light/roughness.ktx2', NULL, 'spatial-assets/materials/counter-concrete-light/ao.ktx2', 'spatial-assets/materials/counter-concrete-light/displacement.ktx2', 2.5, 0.65, ARRAY['beton', 'concrete', 'hell', 'light', 'arbeitsplatte']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Concrete046","roughness":0.9,"metalness":0,"fallback_color_hex":"#BDBBB6","thumbnail_path":"spatial-assets/materials/thumbnails/counter-concrete-light.jpg"}'::jsonb),
  ('counter-concrete-dark', 'Beton Anthrazit', 'concrete', 'counter', 'Beton & Quarz', 'spatial-assets/materials/counter-concrete-dark/albedo.ktx2', 'spatial-assets/materials/counter-concrete-dark/normal.ktx2', 'spatial-assets/materials/counter-concrete-dark/roughness.ktx2', NULL, 'spatial-assets/materials/counter-concrete-dark/ao.ktx2', 'spatial-assets/materials/counter-concrete-dark/displacement.ktx2', 2.5, 0.65, ARRAY['beton', 'concrete', 'anthrazit', 'dark', 'arbeitsplatte']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Concrete031","roughness":0.9,"metalness":0,"fallback_color_hex":"#54534F","thumbnail_path":"spatial-assets/materials/thumbnails/counter-concrete-dark.jpg"}'::jsonb),
  ('metal-chrome', 'Chrom Poliert', 'metal', 'metal', 'Metall', 'spatial-assets/materials/metal-chrome/albedo.ktx2', 'spatial-assets/materials/metal-chrome/normal.ktx2', 'spatial-assets/materials/metal-chrome/roughness.ktx2', 'spatial-assets/materials/metal-chrome/metallic.ktx2', 'spatial-assets/materials/metal-chrome/ao.ktx2', 'spatial-assets/materials/metal-chrome/displacement.ktx2', 0.05, 0.05, ARRAY['chrom', 'chrome', 'metall', 'metal', 'poliert', 'glanz']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Metal049A","roughness":0.08,"metalness":1,"fallback_color_hex":"#D6D8DB","thumbnail_path":"spatial-assets/materials/thumbnails/metal-chrome.jpg"}'::jsonb),
  ('metal-steel-brushed', 'Edelstahl Gebürstet', 'metal', 'metal', 'Metall', 'spatial-assets/materials/metal-steel-brushed/albedo.ktx2', 'spatial-assets/materials/metal-steel-brushed/normal.ktx2', 'spatial-assets/materials/metal-steel-brushed/roughness.ktx2', 'spatial-assets/materials/metal-steel-brushed/metallic.ktx2', 'spatial-assets/materials/metal-steel-brushed/ao.ktx2', 'spatial-assets/materials/metal-steel-brushed/displacement.ktx2', 0.2, 0.2, ARRAY['edelstahl', 'stahl', 'steel', 'gebürstet', 'brushed', 'metall']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Metal032","roughness":0.4,"metalness":1,"fallback_color_hex":"#A7A9AC","thumbnail_path":"spatial-assets/materials/thumbnails/metal-steel-brushed.jpg"}'::jsonb),
  ('metal-brass', 'Messing', 'metal', 'metal', 'Metall', 'spatial-assets/materials/metal-brass/albedo.ktx2', 'spatial-assets/materials/metal-brass/normal.ktx2', 'spatial-assets/materials/metal-brass/roughness.ktx2', 'spatial-assets/materials/metal-brass/metallic.ktx2', 'spatial-assets/materials/metal-brass/ao.ktx2', 'spatial-assets/materials/metal-brass/displacement.ktx2', 0.05, 0.05, ARRAY['messing', 'brass', 'gold', 'metall', 'metal']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Metal034","roughness":0.25,"metalness":1,"fallback_color_hex":"#C9A86A","thumbnail_path":"spatial-assets/materials/thumbnails/metal-brass.jpg"}'::jsonb),
  ('metal-black-matte', 'Schwarz Matt', 'metal', 'metal', 'Metall', 'spatial-assets/materials/metal-black-matte/albedo.ktx2', 'spatial-assets/materials/metal-black-matte/normal.ktx2', 'spatial-assets/materials/metal-black-matte/roughness.ktx2', 'spatial-assets/materials/metal-black-matte/metallic.ktx2', 'spatial-assets/materials/metal-black-matte/ao.ktx2', 'spatial-assets/materials/metal-black-matte/displacement.ktx2', 0.1, 0.1, ARRAY['schwarz', 'black', 'matt', 'matte', 'metall', 'metal']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Metal046A","roughness":0.6,"metalness":1,"fallback_color_hex":"#2A2A2C","thumbnail_path":"spatial-assets/materials/thumbnails/metal-black-matte.jpg"}'::jsonb),
  ('decor-linen', 'Leinen Stoff', 'fabric', 'decor', 'Stoff & Leder', 'spatial-assets/materials/decor-linen/albedo.ktx2', 'spatial-assets/materials/decor-linen/normal.ktx2', 'spatial-assets/materials/decor-linen/roughness.ktx2', NULL, 'spatial-assets/materials/decor-linen/ao.ktx2', 'spatial-assets/materials/decor-linen/displacement.ktx2', 1.2, 1.2, ARRAY['leinen', 'linen', 'stoff', 'fabric', 'textil']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Fabric061","roughness":0.9,"metalness":0,"fallback_color_hex":"#CFC6B4","thumbnail_path":"spatial-assets/materials/thumbnails/decor-linen.jpg"}'::jsonb),
  ('decor-leather-brown', 'Leder Braun', 'fabric', 'decor', 'Stoff & Leder', 'spatial-assets/materials/decor-leather-brown/albedo.ktx2', 'spatial-assets/materials/decor-leather-brown/normal.ktx2', 'spatial-assets/materials/decor-leather-brown/roughness.ktx2', NULL, 'spatial-assets/materials/decor-leather-brown/ao.ktx2', 'spatial-assets/materials/decor-leather-brown/displacement.ktx2', 0.8, 0.8, ARRAY['leder', 'leather', 'braun', 'brown', 'stoff']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Leather037","roughness":0.9,"metalness":0,"fallback_color_hex":"#6B4528","thumbnail_path":"spatial-assets/materials/thumbnails/decor-leather-brown.jpg"}'::jsonb),
  ('decor-ceramic-white', 'Keramik Weiß', 'ceramic', 'decor', 'Keramik & Glas', 'spatial-assets/materials/decor-ceramic-white/albedo.ktx2', 'spatial-assets/materials/decor-ceramic-white/normal.ktx2', 'spatial-assets/materials/decor-ceramic-white/roughness.ktx2', NULL, 'spatial-assets/materials/decor-ceramic-white/ao.ktx2', 'spatial-assets/materials/decor-ceramic-white/displacement.ktx2', 0.4, 0.4, ARRAY['keramik', 'ceramic', 'weiß', 'white', 'glanz']::text[], false, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":"Tiles107","roughness":0.3,"metalness":0,"fallback_color_hex":"#F0EFEC","thumbnail_path":"spatial-assets/materials/thumbnails/decor-ceramic-white.jpg"}'::jsonb),
  ('decor-mirror', 'Spiegel', 'other', 'decor', 'Keramik & Glas', NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, ARRAY['spiegel', 'mirror', 'glas', 'glass', 'reflexion']::text[], true, 'CC0-1.0', NULL, 'ambientcg', true, '{"acg_id":null,"roughness":0.05,"metalness":1,"fallback_color_hex":"#C8D0D6","thumbnail_path":"spatial-assets/materials/thumbnails/decor-mirror.jpg"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  category = EXCLUDED.category,
  surface_category = EXCLUDED.surface_category,
  section = EXCLUDED.section,
  albedo_path = EXCLUDED.albedo_path,
  normal_path = EXCLUDED.normal_path,
  roughness_path = EXCLUDED.roughness_path,
  metallic_path = EXCLUDED.metallic_path,
  ao_path = EXCLUDED.ao_path,
  displacement_path = EXCLUDED.displacement_path,
  tile_scale_u_m = EXCLUDED.tile_scale_u_m,
  tile_scale_v_m = EXCLUDED.tile_scale_v_m,
  tags = EXCLUDED.tags,
  is_procedural = EXCLUDED.is_procedural,
  license = EXCLUDED.license,
  attribution = EXCLUDED.attribution,
  vendor = EXCLUDED.vendor,
  published = EXCLUDED.published,
  metadata = EXCLUDED.metadata,
  updated_at = now();
